// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Trace struct {
	ID         uuid.UUID       `json:"id"`
	Name       string          `json:"name"`
	Status     string          `json:"status"`
	StartedAt  time.Time       `json:"started_at"`
	FinishedAt *time.Time      `json:"finished_at"`
	DurationMs *int64          `json:"duration_ms"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
}

type TraceEvent struct {
	ID         uuid.UUID       `json:"id"`
	TraceID    uuid.UUID       `json:"trace_id"`
	EventType  string          `json:"event_type"`
	Message    *string         `json:"message"`
	Timestamp  time.Time       `json:"timestamp"`
	DurationMs *int64          `json:"duration_ms"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
}
