// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createTrace = `-- name: CreateTrace :one
INSERT INTO traces (name, status, metadata)
VALUES ($1, $2, $3)
RETURNING id, name, status, started_at, finished_at, duration_ms, metadata, created_at
`

type CreateTraceParams struct {
	Name     string          `json:"name"`
	Status   string          `json:"status"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, createTrace, arg.Name, arg.Status, arg.Metadata)
	var item Trace
	err := row.Scan(
		&item.ID,
		&item.Name,
		&item.Status,
		&item.StartedAt,
		&item.FinishedAt,
		&item.DurationMs,
		&item.Metadata,
		&item.CreatedAt,
	)
	return item, err
}

const getTrace = `-- name: GetTrace :one
SELECT id, name, status, started_at, finished_at, duration_ms, metadata, created_at
FROM traces
WHERE id = $1
`

func (q *Queries) GetTrace(ctx context.Context, id uuid.UUID) (Trace, error) {
	row := q.db.QueryRow(ctx, getTrace, id)
	var item Trace
	err := row.Scan(
		&item.ID,
		&item.Name,
		&item.Status,
		&item.StartedAt,
		&item.FinishedAt,
		&item.DurationMs,
		&item.Metadata,
		&item.CreatedAt,
	)
	return item, err
}

const listTraces = `-- name: ListTraces :many
SELECT id, name, status, started_at, finished_at, duration_ms, metadata, created_at
FROM traces
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListTraces(ctx context.Context, limit int32) ([]Trace, error) {
	rows, err := q.db.Query(ctx, listTraces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]Trace, 0)
	for rows.Next() {
		var item Trace
		if err := rows.Scan(
			&item.ID,
			&item.Name,
			&item.Status,
			&item.StartedAt,
			&item.FinishedAt,
			&item.DurationMs,
			&item.Metadata,
			&item.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

const listTracesByStatus = `-- name: ListTracesByStatus :many
SELECT id, name, status, started_at, finished_at, duration_ms, metadata, created_at
FROM traces
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTracesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListTracesByStatus(ctx context.Context, arg ListTracesByStatusParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, listTracesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]Trace, 0)
	for rows.Next() {
		var item Trace
		if err := rows.Scan(
			&item.ID,
			&item.Name,
			&item.Status,
			&item.StartedAt,
			&item.FinishedAt,
			&item.DurationMs,
			&item.Metadata,
			&item.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

const transitionTrace = `-- name: TransitionTrace :one
UPDATE traces
SET status = $3,
    finished_at = $4,
    duration_ms = $5
WHERE id = $1
  AND status = $2
RETURNING id, name, status, started_at, finished_at, duration_ms, metadata, created_at
`

type TransitionTraceParams struct {
	ID         uuid.UUID  `json:"id"`
	Status     string     `json:"status"`
	Status_2   string     `json:"status_2"`
	FinishedAt *time.Time `json:"finished_at"`
	DurationMs *int64     `json:"duration_ms"`
}

func (q *Queries) TransitionTrace(ctx context.Context, arg TransitionTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, transitionTrace, arg.ID, arg.Status, arg.Status_2, arg.FinishedAt, arg.DurationMs)
	var item Trace
	err := row.Scan(
		&item.ID,
		&item.Name,
		&item.Status,
		&item.StartedAt,
		&item.FinishedAt,
		&item.DurationMs,
		&item.Metadata,
		&item.CreatedAt,
	)
	return item, err
}

const createTraceEvent = `-- name: CreateTraceEvent :one
INSERT INTO trace_events (trace_id, event_type, message, duration_ms, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, trace_id, event_type, message, timestamp, duration_ms, metadata, created_at
`

type CreateTraceEventParams struct {
	TraceID    uuid.UUID       `json:"trace_id"`
	EventType  string          `json:"event_type"`
	Message    *string         `json:"message"`
	DurationMs *int64          `json:"duration_ms"`
	Metadata   json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateTraceEvent(ctx context.Context, arg CreateTraceEventParams) (TraceEvent, error) {
	row := q.db.QueryRow(ctx, createTraceEvent, arg.TraceID, arg.EventType, arg.Message, arg.DurationMs, arg.Metadata)
	var item TraceEvent
	err := row.Scan(
		&item.ID,
		&item.TraceID,
		&item.EventType,
		&item.Message,
		&item.Timestamp,
		&item.DurationMs,
		&item.Metadata,
		&item.CreatedAt,
	)
	return item, err
}

const listTraceEvents = `-- name: ListTraceEvents :many
SELECT id, trace_id, event_type, message, timestamp, duration_ms, metadata, created_at
FROM trace_events
WHERE trace_id = $1
ORDER BY timestamp ASC, created_at ASC
`

func (q *Queries) ListTraceEvents(ctx context.Context, traceID uuid.UUID) ([]TraceEvent, error) {
	rows, err := q.db.Query(ctx, listTraceEvents, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	items := make([]TraceEvent, 0)
	for rows.Next() {
		var item TraceEvent
		if err := rows.Scan(
			&item.ID,
			&item.TraceID,
			&item.EventType,
			&item.Message,
			&item.Timestamp,
			&item.DurationMs,
			&item.Metadata,
			&item.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}
